export const ROUTES = {
  SPLASH: '/splash',
  TABS: '/(tabs)',
  DASHBOARD: '/(tabs)',
  RESIDENTS: '/(tabs)/residents',
  VISITORS: '/(tabs)/visitors',
  MAINTENANCE: '/(tabs)/maintenance',
  AMENITIES: '/(tabs)/amenities',
  NOTICES: '/(tabs)/notices',
  SETTINGS: '/(tabs)/settings',
  PROFILE: '/(tabs)/profile',
  SOCIETY: '/society',
} as const;

export const STRINGS = {
  appName: 'NivassHub',
  tagline: 'Modern Society Management',
  welcomeMessage: 'Welcome to NivassHub',
  splashText: 'NivassHub',
  dashboard: 'Dashboard',
  residents: 'Residents',
  visitors: 'Visitors',
  maintenance: 'Maintenance',
  amenities: 'Amenities',
  notices: 'Notices',
  profile: 'Profile',
  settings: 'Settings',
  totalResidents: 'Total Residents',
  totalFlats: 'Total Flats',
  activeVisitors: 'Active Visitors',
  pendingComplaints: 'Pending Complaints',
  recentActivities: 'Recent Activities',
  noData: 'No data available',
  loading: 'Loading...',
  search: 'Search...',
  version: '1.0.0',
  societyName: 'NivassHub Residential Society',
  societyAddress: '123 Society Road, Green Valley, Bengaluru – 560001',
} as const;
